spring:
  application:
    name: employees-resume-project
  profiles:
    active: development # production development
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      enabled: true
      failFast: false
      uri: http://host.docker.internal:8888/ # or ip inside docker conteiner or localhost for local using
