spring:
  application:
    name: employees-resume-project
  profiles:
    active: development # production development
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      enabled: true
      failFast: false
#      uri: https://spring-boot-cloud-config.herokuapp.com/
      uri: http://localhost:8888/ # only for local using
