spring:
  application:
    name: employees-resume-project
  profiles:
    active: development # production development
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      enabled: true
      failFast: false
      uri: http://spring-boot-cloud-configuration:8888/ # only for local using
