spring:
  application:
    name: employees-resume-project
  profiles:
    active: development # production development
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      enabled: true
      failFast: false
      uri: http://6482fcc66c545809cfc88597f4244db4c96be198b885f500af9a2c7bbc662e60:8888/ # only for local using
